services:
  react:
    container_name: ap-react-dev
    build:
      context: ./react_page
      dockerfile: Dockerfile.dev
      args:
        VITE_APP_API_ADDRESS: http://127.0.0.1:8000/api/
    ports:
      - "5173:5173"
    volumes:
      - ./react_page:/app
      - /app/node_modules

  django:
    container_name: ap-django-dev
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file:
      - ./.env.dev
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./service_key.json

  db:
    container_name: ap-db-dev
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postresql/data/
    environment:
      - POSTGRES_USER=ap_user
      - POSTGRES_PASSWORD=44use98
      - POSTGRES_DB=ap-db-dev

volumes:
  postgres_data:
