# Generated by Django 4.2.2 on 2026-01-27 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('path', models.CharField(blank=True, max_length=250, null=True, verbose_name='Path')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Comment body', max_length=1000, verbose_name='Body')),
                ('timestamp', models.CharField(blank=True, max_length=5, null=True, verbose_name='Timestamp')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='songs.comment')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.song')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('songs.comment',),
        ),
    ]
