version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postresql/data/
    environment:
      - POSTGRES_USER=ap_user
      - POSTGRES_PASSWORD=44use98
      - POSTGRES_DB=audio_player

volumes:
  postgres_data:
