FROM python:3.11-slim-bookworm

WORKDIR /app
EXPOSE 8000

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_ROOT_USER_ACTION=ignore

# Install system dependencies
RUN apt-get update && apt-get install -y netcat-openbsd

# Install Python dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt ./
RUN pip install -r requirements.txt

# Copy project files
COPY . /app/

# Set up entrypoint
RUN sed -i 's/\r$//g' /app/entrypoint.dev.sh && \
    chmod +x /app/entrypoint.dev.sh

ENTRYPOINT ["/app/entrypoint.dev.sh"]
