FROM python:3.11-slim-bookworm

WORKDIR /app
EXPOSE 8000

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip

COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y netcat-openbsd

COPY . /app

COPY ./entrypoint.dev.sh .
RUN sed -i 's/\r$//g' /app/entrypoint.dev.sh
RUN chmod +x /app/entrypoint.dev.sh
ENTRYPOINT ["/app/entrypoint.dev.sh"]
