# Generated by Django 4.2.2 on 2023-07-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("audio_player", "0004_alter_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="song",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="audio_player.song",
            ),
        ),
    ]
