# Generated by Django 4.2.2 on 2023-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio_player", "0006_alter_comment_parent_alter_comment_song_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated at"
            ),
        ),
    ]
