# Generated by Django 4.2.2 on 2023-08-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_player', '0012_remove_comment_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='path',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Path'),
        ),
    ]
