# Generated by Django 4.2.2 on 2023-08-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_player', '0013_song_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('audio_player.comment',),
        ),
    ]
