FROM node:20-alpine

WORKDIR /app

COPY package.json ./

RUN npm install
RUN NODE_OPTIONS="--max-old-space-size=4096"

COPY . .

ARG VITE_APP_API_ADDRESS
ENV VITE_APP_API_ADDRESS $VITE_APP_API_ADDRESS

EXPOSE 5173

CMD ["npm", "run", "dev"]
